import { Analytics } from "@vercel/analytics/react"
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <Analytics/>
      <body>{children}</body>
    </html>
  );
}
